[versions]
kotlin = "2.0.0"
ktor = "3.3.2"
room = "2.8.3"
firebase = "32.3.1"
lifecycleViewmodelKtx = "2.9.4"
runtime = "1.9.4"
composeMaterial3 = "1.5.5"
material3 = "1.4.0"
foundation = "1.9.4"
activityKtx = "1.11.0"
firebaseFirestoreKtx = "26.0.2"
navigationCompose = "2.9.6"
foundationLayout = "1.9.4"

[libraries]
ktor-client-core = { module = "io.ktor:ktor-client-core", version.ref = "ktor" }
ktor-client-cio = { module = "io.ktor:ktor-client-cio", version.ref = "ktor" }

room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }

firebase-firestore = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebase" }
lifecycle-viewmodel-ktx = { group = "androidx.lifecycle", name = "lifecycle-viewmodel-ktx", version.ref = "lifecycleViewmodelKtx" }
runtime = { group = "androidx.compose.runtime", name = "runtime", version.ref = "runtime" }
compose-material3 = { group = "androidx.wear.compose", name = "compose-material3", version.ref = "composeMaterial3" }
material3 = { group = "androidx.compose.material3", name = "material3", version.ref = "material3" }
foundation = { group = "androidx.compose.foundation", name = "foundation", version.ref = "foundation" }
activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activityKtx" }
firebase-firestore-ktx = { group = "com.google.firebase", name = "firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }
foundation-layout = { group = "androidx.compose.foundation", name = "foundation-layout", version.ref = "foundationLayout" }

[plugins]
org-jetbrains-kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }


